path = ["/Users/oem/.cabal/bin", "/Users/oem/.ghcup/bin", "/Users/oem/.volta/bin", "/usr/local/opt/binutils/bin", "/Users/oem/.poetry/bin", "/Users/oem/.fzf/bin", "/Users/oem/.rbenv/shims", "/Users/oem/.rbenv/shims", "/Users/oem/.rbenv/bin", "/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims", "/Users/oem/.pyenv/shims", "/Users/oem/.pyenv/bin", "/Library/Developer/Toolchains/swift-latest/usr/bin", "/Users/oem/.cargo/bin", "/Users/oem/src/go/bin", "/Users/oem/bin", "/Users/oem/google-cloud-sdk/bin", "/Users/oem/dotfiles/fuzzy", "/Users/oem/dotfiles/launch", "/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/opt/X11/bin", "/Library/Apple/usr/bin", "/Library/TeX/texbin"]
prompt = "STARSHIP_SHELL= starship prompt"
skip_welcome_message = true

startup = [
	"alias vi = nvim",
	"alias l = ls -la",
	"alias cat = bat -p",
	"alias b = bundle exec",
	"alias c = cargo",
	"alias dc = docker-compose",
	]

[env]
ALACRITTY_LOG = "/var/folders/wv/13hkc2xs4l5dft4rzpq9zkhh0000gn/T/Alacritty-27838.log"
CMD_DURATION = "2.380503ms"
COLORTERM = "truecolor"
COMMAND_MODE = "unix2003"
DISPLAY = "/private/tmp/com.apple.launchd.kf1lbqbzcr/org.macosforge.xquartz:0"
EDITOR = "nvim"
FZF_DEFAULT_COMMAND = "fd --type f"
GOBIN = "/Users/oem/src/go/bin"
GOPATH = "/Users/oem/src/go"
HOME = "/Users/oem"
HOMEBREW_GITHUB_API_TOKEN = "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"
LANG = "en_US.UTF-8"
LANGUAGE = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
LC_CTYPE = "UTF-8"
LOGNAME = "oem"
NODE_PATH = "/usr/local/lib/node_modules"
N_PREFIX = "/Users/oem"
PWD = "/Users/oem"
PYENV_ROOT = "/Users/oem/.pyenv"
PYENV_SHELL = "nu"
PYENV_VIRTUALENV_INIT = "1"
RBENV_SHELL = "nu"
RUST_SRC_PATH = "/Users/oem/src/rust/src"
SHELL = "/Users/oem/.cargo/bin/nu"
SHLVL = "1"
SSH_AGENT_PID = "828"
SSH_AUTH_SOCK = "/var/folders/wv/13hkc2xs4l5dft4rzpq9zkhh0000gn/T//ssh-75etQpnSgnFV/agent.826"
SSH_ENV = "/Users/oem/.ssh/environment"
STARSHIP_SESSION_KEY = "8180547359856298"
STARSHIP_SHELL = "nu"
TERM = "xterm-256color"
TMPDIR = "/var/folders/wv/13hkc2xs4l5dft4rzpq9zkhh0000gn/T/"
USER = "oem"
VOLTA_HOME = "/Users/oem/.volta"
XDG_CONFIG_HOME = "/Users/oem/.config"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "application.io.alacritty.38319378.38319381"
__CFBundleIdentifier = "io.alacritty"
__CF_USER_TEXT_ENCODING = "0x1F5:0x0:0x0"
pure_symbol_prompt = ""
