path = ["/home/oem/.volta/bin", "/usr/local/opt/binutils/bin", "/home/oem/.rbenv/shims", "/home/oem/.rbenv/shims", "/home/oem/.rbenv/bin", "/home/oem/.local/bin", "/home/oem/.pyenv/shims", "/Library/Developer/Toolchains/swift-latest/usr/bin", "/home/oem/.cargo/bin", "/home/oem/src/go/bin", "/home/oem/bin", "/home/oem/google-cloud-sdk/bin", "/home/oem/src/oem/dotfiles/fuzzy", "/home/oem/src/oem/dotfiles/launch", "/home/oem/.volta/bin", "/home/oem/.rbenv/shims", "/home/oem/.rbenv/shims", "/home/oem/.rbenv/bin", "/home/oem/.local/bin", "/home/oem/.pyenv/shims", "/Library/Developer/Toolchains/swift-latest/usr/bin", "/home/oem/.cargo/bin", "/home/oem/src/go/bin", "/home/oem/bin", "/home/oem/google-cloud-sdk/bin", "/home/oem/src/oem/dotfiles/fuzzy", "/home/oem/src/oem/dotfiles/launch", "/usr/local/sbin", "/usr/local/bin", "/usr/bin", "/usr/bin/site_perl", "/usr/bin/vendor_perl", "/usr/bin/core_perl"]
prompt = "STARSHIP_SHELL= starship prompt"
skip_welcome_message = true
startup = ["alias vi = nvim", "alias l = ls", "alias cat = bat -p", "alias b = bundle exec", "alias c = cargo", "alias dc = docker-compose"]

[env]
CMD_DURATION_MS = "0"
COLORFGBG = "default;default"
COLORTERM = "rxvt-xpm"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
DISPLAY = ":0"
EDITOR = "nvim"
FZF_DEFAULT_COMMAND = "fd --type f"
GOBIN = "/home/oem/src/go/bin"
GOPATH = "/home/oem/src/go"
HOME = "/home/oem"
INVOCATION_ID = "d55684d7f1df4c348c12d6c92f565feb"
JOURNAL_STREAM = "8:31778"
LANG = "en_US.UTF-8"
LANGUAGE = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
LOGNAME = "oem"
MAIL = "/var/spool/mail/oem"
MOTD_SHOWN = "pam"
NODE_PATH = "/usr/local/lib/node_modules"
N_PREFIX = "/home/oem"
PYENV_ROOT = "/home/oem/.pyenv"
PYENV_SHELL = "nu"
RBENV_SHELL = "nu"
RUST_SRC_PATH = "/home/oem/src/rust/src"
SHELL = "/usr/bin/nu"
SHLVL = "4"
SSH_ENV = "/home/oem/.ssh/environment"
STARSHIP_SESSION_KEY = "1561636769275419"
STARSHIP_SHELL = "nu"
TERM = "xterm-256color"
USER = "oem"
VOLTA_HOME = "/home/oem/.volta"
WINDOWID = "12584968"
WINDOWPATH = "1"
XAUTHORITY = "/home/oem/.Xauthority"
XDG_CONFIG_HOME = "/home/oem/.config"
XDG_RUNTIME_DIR = "/run/user/1000"
XDG_SEAT = "seat0"
XDG_SESSION_CLASS = "user"
XDG_SESSION_ID = "1"
XDG_SESSION_TYPE = "tty"
XDG_VTNR = "1"
