Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets
