#!/bin/sh
# launches the script from param in a centered window
xdotool search --onlyvisible --classname URxvtFuzzy windowunmap \
  || xdotool search --classname URxvtFuzzy windowmap \
  || urxvtc -name URxvtFuzzy -geometry 40x4+730 -e $1

