#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width  0
bspc config window_gap   20

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Inox desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a \*:"URxvtQuake" state=floating center=on sticky=on
bspc rule -a \*:"URxvtFuzzy" state=floating center=on sticky=on

bspc desktop II --layout monocle

